"""empty message

Revision ID: 82ea62038643
Revises: f4a665b60d37
Create Date: 2023-08-11 02:47:31.918531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ea62038643'
down_revision = 'f4a665b60d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('link_to_page')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_to_page', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
