"""empty message

Revision ID: f4a665b60d37
Revises: 1375928bc8d5
Create Date: 2023-08-11 02:43:02.274038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a665b60d37'
down_revision = '1375928bc8d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('og_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('link_to_page', sa.String(length=200), nullable=True))
        batch_op.drop_constraint('favorites_character_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_planet_id_fkey', type_='foreignkey')
        batch_op.drop_column('character_id')
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favorites_planet_id_fkey', 'planet', ['planet_id'], ['id'])
        batch_op.create_foreign_key('favorites_character_id_fkey', 'character', ['character_id'], ['id'])
        batch_op.drop_column('link_to_page')
        batch_op.drop_column('og_id')
        batch_op.drop_column('type')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
